// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uexvqdqeilkmtcvjcssr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVleHZxZHFlaWxrbXRjdmpjc3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODgwOTAsImV4cCI6MjA3MTE2NDA5MH0.NK5FYQ0RtD5TJUFn_RPRWmHWomMgXj21UUBvjG0rqtk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});